language: perl
perl:
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
before_install:
  - cpanm Test::MockTime
install:
  - cpanm -v --installdeps --notest .
script: "perl Build.PL; ./Build test"
notifications:
  recipients:
    - captindave@gmail.com
  email:
    on_success: change
    on_failure: always
